version: '3.4'
services:
  elasticsearch-default-1:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.6.2'
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ports:
      - '9200:9200'